create table TbCorona19CountStatus_bulk1(
    S_DT    text,
    S_HJ    text,
    SN_HJ    text,
    S_CARE    text,
    S_RECOVER    text,
    SN_RECOVER    text,
    S_DEATH    text,
    SY_TOTAL    text,
    SY_KJ    text,
    SY_KH    text,
    T_DT    text,
    T_HJ    text,
    N_HJ    text,
    TY_CARE    text,
    RECOVER    text,
    DEATH    text,
    TY_TOTAL    text,
    TY_KJ    text,
    TY_KH    text,
    JGK_OVERSEAS_GS    text,
    JGK_OVERSEAS_GH    text,
    JGK_CONT_GS    text,
    JGK_CONT_GH    text,
    CHECKING    text,
    DAY_DEATH    text,
    ALL_DAY_DEATH    text
)
